### ISSUE TITLE
Ranking da igualdade racial.

### ISSUE THREAD

**Issue by FeresJoao** [iesp-uerj/olb#25]

**Comment by jcanello** [comment]
Primeira listagem de proposições para análise enviada por e-mail e disponível no drive.
https://drive.google.com/file/d/1b3jKJWOpqWnmb_ZljzQdr8SusrLk2DMr/view?usp=sharing

**Comment by AndreFelixIESP** [comment]
Dados dos PLs raspados. Detalhes no issue: https://github.com/iesp-uerj/olb-app/issues/36

**Comment by AndreFelixIESP** [comment]
Ranking no ar: https://olb.org.br/observatorio/
Ref https://github.com/iesp-uerj/olb-wp/issues/74
